#!/bin/bash
##obliczanienie sk

#find . -regex ".*jmol_99[0-9][0-9][0-9]00\.jmol" | while read f; do
ls *.jmol | while read f; do
    #NR="`echo $f | cut -f2 -d_ | cut -f1 -d.`"
    #if [ $NR -ge 5000000 ] && [ $(( NR % 1000 )) == 0 ]; then
        ROOT_NAME="`echo ${f} | cut -f1 -d.`"
        if [ ! -f "${ROOT_NAME}.jsff" ]; then
            echo "FILE: ${f}"
            ./SkAVG 1 "${f}" config.txt
        fi
    #fi
done

cat *.jsff >> out.all
./SkAVG 2 out.all
rm out.all
